apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-tester
  namespace: flux-tester
spec:
  releaseName: flux-tester
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: flux-tester
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    diagnosticMode:
      enabled: false